#pragma once
#include <Core/defines.h>
#include <Core/engine.h>
#include <render/window.h>
#include <render/renderer.h>
#include <components/transform_component.h>
#include <components/camera_component.h>
#include <Core/input.h>
#include <Core/keys.h>
#include <Core/Scene.h>